// There are two data-type primitive and non-primitive data types

// primitive data type\

// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol construct

let number = 1;
let str = 'word';
let Booleans = true;
let emptyValue = null;
let variableWithoutValue = undefined;


// non primitive data-types

// Objects
// Arrays

// list of values we will be store in the non- primitive data-type

let list = ['array', 1.09, 8, true, null, undefined];

let obj = {
    name: 'sibi',
    age: 20,
    city: 'chennai'    
}